# Generated by Django 2.1.4 on 2019-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_module', '0004_auto_20190301_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedocument',
            name='external_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
