# Generated by Django 2.1.4 on 2019-03-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('rut', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('external_operation_id', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricBillingContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=200)),
                ('address_number', models.IntegerField()),
                ('street_address', models.CharField(max_length=350)),
                ('adition_info_address', models.CharField(max_length=350)),
                ('base_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_module.BillingContact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='billing_contact_for_billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing_module.HistoricBillingContact'),
        ),
    ]
