# Generated by Django 2.1.4 on 2019-03-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_module', '0002_auto_20190304_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingContact',
            new_name='BillingPayer',
        ),
    ]
