# Generated by Django 2.1.5 on 2019-03-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('number_account', models.CharField(max_length=150)),
                ('destiny_account_type', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDestiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DestinyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('destiny_account_name', models.CharField(max_length=150)),
                ('destiny_account_document_number', models.CharField(max_length=150)),
                ('destiny_account_email', models.EmailField(max_length=254)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_transfers_module.BankAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('gloss', models.CharField(max_length=150)),
                ('transfer_request_date', models.DateTimeField()),
                ('external_account_id', models.CharField(max_length=150)),
                ('external_transacction_id', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('transfer_confirmation_date', models.DateTimeField(null=True)),
                ('destiny_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_transfers_module.DestinyAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_transfers_module.BankDestiny'),
        ),
    ]
