# Generated by Django 2.1.4 on 2019-03-26 15:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import engine.models.batches


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('external_account_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('account_type', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('external_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20, validators=[engine.models.batches.positive_number])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DWHBalanceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('balance_account_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('gloss', models.TextField(max_length=350)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='engine.Batch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('document_number', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Account')),
                ('financing_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.account',),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('posting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Posting')),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.posting',),
        ),
        migrations.AddField(
            model_name='posting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Account'),
        ),
        migrations.AddField(
            model_name='posting',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='engine.AssetType'),
        ),
        migrations.AddField(
            model_name='posting',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='engine.Journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='engine.JournalTransactionType'),
        ),
        migrations.AddField(
            model_name='dwhbalanceaccount',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='external_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='real_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.RealAccount'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account_payer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='account_payer', to='engine.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('external_account_id', 'external_account_type')},
        ),
    ]
