# Generated by Django 2.1.5 on 2019-03-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_operationaccount_requester_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bank_account_number', models.IntegerField()),
                ('account_notification_email', models.EmailField(max_length=254)),
                ('bank_code', models.IntegerField()),
                ('account_bank_type', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
