# Generated by Django 2.1.4 on 2018-12-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20181226_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='engine.BatchState'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='posting',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
