# Generated by Django 2.1.5 on 2019-04-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder_document_number',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
