# Generated by Django 2.1.5 on 2019-04-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20190403_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('operation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='engine.OperationAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
