# Generated by Django 2.1.4 on 2018-12-27 19:50

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import engine.models.batches


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20181227_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=20, validators=[engine.models.batches.positive_number]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='engine.Batch'),
        ),
    ]
