# Generated by Django 2.1.4 on 2019-02-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20190228_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Account')),
                ('financing_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.account',),
        ),
    ]
