# Generated by Django 2.1.4 on 2019-02-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_operationaccount_external_operacion_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_request',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Account')),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('destiny_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='engine.Account')),
                ('origin_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='engine.Account')),
            ],
            options={
                'abstract': False,
            },
            bases=('engine.account',),
        ),
        migrations.AlterField(
            model_name='operationaccount',
            name='external_operacion_account_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
