# Generated by Django 2.1.4 on 2019-02-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20190228_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('destiny_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='engine.Account')),
                ('origin_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='engine.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment_request',
            name='account_ptr',
        ),
        migrations.RemoveField(
            model_name='payment_request',
            name='destiny_account',
        ),
        migrations.RemoveField(
            model_name='payment_request',
            name='origin_account',
        ),
        migrations.DeleteModel(
            name='Payment_request',
        ),
    ]
