# Generated by Django 2.1.4 on 2019-03-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20190228_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='created',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='updated',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='posting_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Posting'),
            preserve_default=False,
        ),
    ]
