# Generated by Django 2.1.5 on 2019-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_auto_20190312_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_account_id',
            field=models.CharField(max_length=150),
        ),
    ]
