# Generated by Django 2.1.4 on 2018-12-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20181226_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='user',
        ),
    ]
