# Generated by Django 2.1.4 on 2018-12-26 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_remove_batch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='total_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
