# Generated by Django 2.1.4 on 2019-02-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20181227_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='state',
        ),
    ]
