# Generated by Django 2.1.4 on 2019-02-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20190225_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal_transaction_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='journal',
            name='amount',
        ),
        migrations.AlterField(
            model_name='journal',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='engine.Batch'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='engine.Journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_transactions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='engine.models.journals.JournalTransactionType'),
        ),
    ]
