# Generated by Django 2.1.4 on 2019-02-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20190226_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('document_number', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='journal_transactions',
            new_name='journal_transaction',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='real_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.RealAccount'),
        ),
    ]
