# Generated by Django 2.1.4 on 2019-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_operationaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaccount',
            name='external_operacion_account_id',
            field=models.IntegerField(default=None),
        ),
    ]
