# Generated by Django 2.1.4 on 2019-03-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_auto_20190301_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='destiny_account',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='origin_account',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='account_payer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='account_payer', to='engine.Account'),
        ),
    ]
