# Generated by Django 2.1.4 on 2019-03-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20190301_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationaccount',
            name='external_operacion_account_id',
        ),
    ]
