# Generated by Django 2.1.5 on 2019-03-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_remove_operationaccount_external_operacion_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('account_type', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DWHBalanceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('balance_account_amount', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='external_account_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='engine.AccountType'),
        ),
    ]
