# Generated by Django 2.1.5 on 2019-03-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_auto_20190312_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='external_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.AccountType'),
        ),
    ]
