# Generated by Django 2.1.5 on 2019-03-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_auto_20190312_1527'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('external_account_id', 'external_account_type')},
        ),
    ]
